# Generated by Django 3.0.3 on 2020-11-04 11:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201102_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='xero_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Xero Errors', null=True),
        ),
    ]
