# Generated by Django 3.0.3 on 2021-02-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0003_auto_20210201_1145'),
        ('tasks', '0004_auto_20201221_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='payment',
            field=models.ForeignKey(help_text='Reference to Payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero.Payment'),
        ),
    ]
