# Generated by Django 3.0.3 on 2021-11-23 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasklog_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Task response', null=True),
        ),
    ]
