# Generated by Django 3.1.13 on 2021-12-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20211123_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='detail',
            field=models.JSONField(default=dict, help_text='Task response', null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='xero_errors',
            field=models.JSONField(help_text='Xero Errors', null=True),
        ),
    ]
