# Generated by Django 3.2.14 on 2024-11-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0020_expensegroup_export_url'),
        ('tasks', '0009_error_repetition_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(help_text='Reference to Expense group', null=True, on_delete=django.db.models.deletion.PROTECT, to='fyle.expensegroup', unique=True),
        ),
    ]
