# Generated by Django 4.2.20 on 2025-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_tasklog_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='triggered_by',
            field=models.CharField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE'), ('INTERNAL', 'INTERNAL')], help_text='Triggered by', max_length=255, null=True),
        ),
    ]
