# Generated by Django 4.2.20 on 2025-04-11 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_tasklog_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='mapping_error_expense_group_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], help_text='list of mapping expense group ids', size=None),
        ),
    ]
