# Generated by Django 4.2.26 on 2026-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasklog_is_attachment_upload_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='stuck_export_re_attempt_count',
            field=models.IntegerField(default=0, help_text='Stuck export re-attempt count'),
        ),
    ]
