codecov:
  require_ci_to_pass: false
comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes: false
  require_head: false
  show_carryforward_flags: false
coverage:
  precision: 2
  range:
  - 97.0
  - 98.0
  round: down
github_checks:
  annotations: false