version: '3.7'

services:
  api:
    build:
      context: ./
      args:
        CI: ENABLED
    entrypoint: bash run.sh
    restart: unless-stopped
    volumes:
    - ./:/fyle-xero-api
    depends_on:
    - db
    - rabbitmq
    environment:
      SECRET_KEY: thisisthedjangosecretkey
      ALLOWED_HOSTS: "*"
      DEBUG: "False"
      NO_WORKERS: 1
      API_URL: http://localhost:8000/api
      DATABASE_URL: postgres://postgres:postgres@db:5432/xero_db
      DB_HOST: db
      FYLE_BASE_URL: ${FYLE_BASE_URL}
      FYLE_CLIENT_ID: ''
      FYLE_CLIENT_SECRET: ''
      FYLE_REFRESH_TOKEN: ''
      FYLE_APP_URL: ${FYLE_APP_URL}
      FYLE_TOKEN_URI: ${FYLE_TOKEN_URI}
      FYLE_SERVER_URL: ${FYLE_SERVER_URL}
      XERO_BASE_URL: ${XERO_BASE_URL}
      XERO_REDIRECT_URI: ${XERO_REDIRECT_URI}
      XERO_TOKEN_URI: ${XERO_TOKEN_URI}
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5673/?heartbeat=0
  db:
    image: "postgres:15"
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tests/sql_fixtures/reset_db_fixtures/reset_db.sql:/docker-entrypoint-initdb.d/reset_db.sql
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5673:5673'
    volumes:
      - rabbitmq-data:/data/

volumes:
  api:
  rabbitmq-data:
