#!/bin/bash

# Django Settings
export SECRET_KEY=YOUR DJANGO SECRET KEY
export ALLOWED_HOSTS=HOSTS SEPARATED BY COMMAS
export DEBUG=True

# Database Settings
export DB_NAME=POSTGRES DB NAME
export DB_USER=POSTGRES DB USER
export DB_PASSWORD=POSTGRES DB PASSWORD
export DB_HOST=POSTGRES DB
export DB_PORT=POSTGRES DB PORT

# Fyle Settings
export FYLE_BASE_URL=FYLE BASE URL
export FYLE_CLIENT_ID=FYLE CLIENT ID
export FYLE_CLIENT_SECRET=FYLE CLIENT SECRET
export FYLE_TOKEN_URI=FYLE TOKEN URI
export FYLE_JOBS_URL=FYLE JOBS URL

# Xero Settings
export XERO_CLIENT_ID=XERO CLIENT ID
export XERO_CLIENT_SECRET=XERO CLIENT SECRET
export XERO_REDIRECT_URI=XERO REDIRECT URI
export XERO_TOKEN_URI=XERO TOKEN URI