# Generated by Django 3.0.3 on 2020-12-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensegroupsettings',
            table='expense_group_settings',
        ),
    ]
