# Generated by Django 3.0.3 on 2021-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0003_auto_20210201_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='org_id',
            field=models.CharField(help_text='Organization ID', max_length=255, null=True),
        ),
    ]
