# Generated by Django 3.0.3 on 2021-09-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_expense_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='exported',
        ),
    ]
