# Generated by Django 3.0.3 on 2021-10-01 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0005_remove_expense_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='File IDs', null=True, size=None),
        ),
    ]
