# Generated by Django 3.1.14 on 2021-12-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0008_auto_20211206_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensegroupsettings',
            old_name='export_date_type',
            new_name='reimbursable_export_date_type',
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='ccc_export_date_type',
            field=models.CharField(default='current_date', help_text='CCC Export Date', max_length=100),
        ),
    ]
