# Generated by Django 3.1.14 on 2022-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0009_auto_20211220_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.FloatField(help_text='Tax Amount', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_group_id',
            field=models.CharField(help_text='Tax Group ID', max_length=255, null=True),
        ),
    ]
