# Generated by Django 3.1.14 on 2022-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0012_auto_20220909_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(default='PAYMENT_PROCESSING', help_text='state at which the ccc expenses are fetched (PAYMENT_PROCESSING /PAID)', max_length=100),
        ),
    ]
