# Generated by Django 3.1.14 on 2022-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0012_auto_20220923_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroupsettings',
            name='import_card_credits',
            field=models.BooleanField(default=False, help_text='Import Card Credits'),
        ),
    ]
