# Generated by Django 3.1.14 on 2022-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0013_expensegroupsettings_import_card_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='response_logs',
            field=models.JSONField(help_text='Reponse log of the export', null=True),
        ),
    ]
