# Generated by Django 3.1.14 on 2022-09-13 09:46

import apps.fyle.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0013_auto_20220913_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which the ccc expenses are fetched (PAYMENT_PROCESSING /PAID)', max_length=100),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='corporate_credit_card_expense_group_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_ccc_expense_group_fields, help_text='list of fields ccc expenses grouped by', size=None),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='reimbursable_expense_group_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_group_fields, help_text='list of fields reimbursable expense grouped by', size=None),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='reimbursable_expense_state',
            field=models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which the reimbursable expenses are fetched (PAYMENT_PROCESSING / PAID)', max_length=100),
        ),
    ]
