# Generated by Django 3.1.14 on 2022-09-20 11:11

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0014_auto_20220913_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which the ccc expenses are fetched (PAYMENT_PROCESSING /PAID)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='reimbursable_expense_state',
            field=models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which the reimbursable expenses are fetched (PAYMENT_PROCESSING / PAID)', max_length=100, null=True),
        ),
    ]
