# Generated by Django 3.1.14 on 2022-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0014_expensegroup_response_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(help_text='Name of the Fyle employee', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='employee_name',
            field=models.CharField(help_text='Expense Group Employee Name', max_length=100, null=True),
        ),
    ]
