# Generated by Django 3.1.14 on 2023-01-17 06:16

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0015_auto_20221104_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PAID', 'PAID'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING')], default=apps.fyle.models.get_default_ccc_expense_state, help_text='state at which the ccc expenses are fetched (PAYMENT_PROCESSING /PAID)', max_length=100, null=True),
        ),
    ]
