# Generated by Django 3.1.14 on 2022-09-23 06:03

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0015_auto_20220920_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroupsettings',
            name='expense_state',
            field=models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which expenses are fetched (PAYMENT_PROCESSING / PAID)', max_length=100),
        ),
    ]
