# Generated by Django 3.1.14 on 2023-06-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0016_auto_20230117_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='posted_at',
            field=models.DateTimeField(help_text='Date when the money is taken from the bank', null=True),
        ),
    ]
