# Generated by Django 3.2.14 on 2024-02-13 04:50

import apps.fyle.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0037_workspacegeneralsettings_import_suppliers_as_merchants'),
        ('fyle', '0017_expense_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accounting_export_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='expense',
            name='previous_export_state',
            field=models.CharField(help_text='Previous export state', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='workspace',
            field=models.ForeignKey(help_text='To which workspace this expense belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], default=apps.fyle.models.get_default_ccc_expense_state, help_text='state at which the ccc expenses are fetched (PAYMENT_PROCESSING /PAID)', max_length=100, null=True),
        ),
    ]
