# Generated by Django 3.2.14 on 2024-11-07 19:16

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0020_expensegroup_export_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_transaction_id',
            field=models.CharField(blank=True, help_text='Bank Transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='split_expense_grouping',
            field=models.CharField(choices=[('SINGLE_LINE_ITEM', 'SINGLE_LINE_ITEM'), ('MULTIPLE_LINE_ITEM', 'MULTIPLE_LINE_ITEM')], default=apps.fyle.models.get_default_split_expense_grouping, help_text='specify line items for split expenses grouping', max_length=100),
        ),
    ]
