# Generated by Django 3.2.14 on 2024-12-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0022_support_split_expense_grouping'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                create publication events for all tables;
                DO $$
                DECLARE
                        tbl RECORD;
                BEGIN
                        FOR tbl IN
                        SELECT table_schema, table_name
                        FROM information_schema.tables
                        WHERE table_type = 'BASE TABLE' AND table_schema = 'public'
                        LOOP
                        EXECUTE format('ALTER TABLE %I.%I REPLICA IDENTITY FULL', tbl.table_schema, tbl.table_name);
                        END LOOP;
                END $$;
            """,
        ),
    ]
