# Generated by Django 4.2.18 on 2025-01-21 12:32

from django.db import migrations
from apps.internal.helpers import safe_run_sql


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0023_auto_20250108_0817'),
    ]

    operations = safe_run_sql(['fyle-integrations-db-migrations/common/global_shared/functions/json_diff.sql'])
