# Generated by Django 4.2.18 on 2025-01-21 12:32

import logging
from django.db import migrations
from apps.fyle.helpers import load_sql_from_file_safe

logger = logging.getLogger(__name__)

class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0023_auto_20250108_0817'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file_safe('fyle-integrations-db-migrations/common/global_shared/functions/json_diff.sql')
        )
    ]
