# Generated by Django 4.2.20 on 2025-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0024_expense_imported_from'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['accounting_export_summary', 'workspace_id'], name='expenses_account_ff34f0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['fund_source', 'workspace_id'], name='expenses_fund_so_386913_idx'),
        ),
    ]
