# Generated by Django 4.2.18 on 2025-01-21 15:04

import logging
from django.db import migrations
from apps.internal.helpers import safe_run_sql

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0024_auto_20250121_1232'),
    ]

    operations = safe_run_sql(['fyle-integrations-db-migrations/common/global_shared/functions/log_delete_event.sql'])
