# Generated by Django 4.2.18 on 2025-01-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0025_auto_20250121_1504'),
    ]

    operations = [
    ]
