# Generated by Django 4.2.21 on 2025-06-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0028_alter_expense_imported_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroupsettings',
            name='import_card_credits',
        ),
    ]
