# Generated by Django 4.2.26 on 2025-11-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0027_remove_expensegroupsettings_import_card_credits'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace_id', 'report_id'], name='expenses_workspa_ad984e_idx'),
        ),
    ]
