# Generated by Django

from django.db import migrations
from apps.internal.helpers import safe_run_sql

sql_files = [
    'fyle-integrations-db-migrations/xero/functions/delete_workspace.sql',
    'fyle-integrations-db-migrations/xero/functions/re_export_expenses_xero.sql'
]

class Migration(migrations.Migration):

    dependencies = [('fyle', '0029_auto_generated_sql')]

    operations = safe_run_sql(sql_files)
