# Generated by Django

from django.db import migrations
from apps.internal.helpers import safe_run_sql

sql_files = [
    # Xero Specific Functions
    'fyle-integrations-db-migrations/xero/functions/delete_workspace.sql',
    'fyle-integrations-db-migrations/xero/functions/re_export_expenses_xero.sql',
    'fyle-integrations-db-migrations/xero/functions/trigger_auto_import.sql',

    # Global Shared Functions
    'fyle-integrations-db-migrations/common/global_shared/functions/json_diff.sql',
    'fyle-integrations-db-migrations/common/global_shared/functions/log_delete_event.sql',

    # Grouped Functions
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/delete_failed_expenses_qbo_intacct_xero_netsuite.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/delete_test_orgs_schedule.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/log_update_event.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/trigger_auto_import_export.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/update_in_progress_tasks_to_failed.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/ws_org_id.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/functions/ws_search.sql',

    # Global Views
    'fyle-integrations-db-migrations/common/global_shared/views/extended_category_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/extended_employee_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/extended_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/prod_workspaces_view.sql',

    # Global Alert Views
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/_import_logs_fatal_failed_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/import_logs_fatal_failed_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/ormq_count_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/repetition_error_count_view.sql',

    # Grouped Views
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/prod_active_workspaces_view.sql',

    # Grouped Alert Views
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/_django_queue_fatal_tasks_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/_django_queue_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/direct_export_errored_expenses_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/_direct_export_errored_expenses_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/django_queue_fatal_tasks_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/django_queue_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/qbo_intacct_netsuite_xero/views/alerts/inactive_workspaces_view.sql',

    # Xero Specific Views
    'fyle-integrations-db-migrations/xero/views/extended_settings_view.sql',
    'fyle-integrations-db-migrations/xero/views/product_advance_settings_view.sql',
    'fyle-integrations-db-migrations/xero/views/product_export_settings_view.sql',
    'fyle-integrations-db-migrations/xero/views/product_import_settings_view.sql',
    'fyle-integrations-db-migrations/xero/views/extended_expenses_view.sql',

    # Xero Specific Trigger
    'fyle-integrations-db-migrations/xero/triggers/update_logs.sql',
]


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0023_auto_20250108_0817'),
        ('users', '0002_auto_20201228_0813'),
        ('mappings', '0007_auto_20250108_0817'),
        ('tasks', '0010_alter_tasklog_expense_group'),
        ('workspaces', '0042_auto_20250108_0817'),
        ('xero', '0010_bill_is_retired')
    ]

    operations = safe_run_sql(sql_files)
