# Generated by Django

from django.db import migrations
from apps.internal.helpers import safe_run_sql

sql_files = [
    'fyle-integrations-db-migrations/xero/functions/delete_workspace.sql'
]


class Migration(migrations.Migration):

    dependencies = [('internal', '0001_auto_generated_sql')]

    operations = safe_run_sql(sql_files)
