# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('internal', '0007_auto_generated_sql'),
        ('workspaces', '0047_featureconfig')
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                insert into feature_configs (workspace_id, export_via_rabbitmq, fyle_webhook_sync_enabled, created_at, updated_at)
                select id, false, false, now(), now()
                from workspaces
                where NOT EXISTS (
                    select 1
                    from feature_configs
                    where workspace_id = workspaces.id
                );
            """,
            reverse_sql="""
                delete from feature_configs
                where exists (select 1 from feature_configs where workspace_id = feature_configs.workspace_id);
            """
        )
    ]
