# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('workspaces', '0048_alter_featureconfig_fyle_webhook_sync_enabled'), ('internal', '0010_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE feature_configs SET fyle_webhook_sync_enabled = TRUE WHERE fyle_webhook_sync_enabled = FALSE;
            """
        )
    ]
