# Generated by Django 3.0.3 on 2020-11-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_auto_20201101_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(help_text='Xero Tenant name', max_length=255)),
                ('tenant_id', models.CharField(help_text='Xero Tenant id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'tenant_mappings',
                'unique_together': {('tenant_name', 'workspace')},
            },
        ),
    ]
