# Generated by Django 3.0.3 on 2020-11-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20201101_0710'),
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_name', models.CharField(help_text='Xero bank account name', max_length=255, null=True)),
                ('bank_account_id', models.CharField(help_text='Xero bank account id', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'general_mappings',
                'unique_together': {('bank_account_name', 'workspace')},
            },
        ),
    ]
