# Generated by Django 3.0.3 on 2021-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_auto_20210201_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmapping',
            name='connection_id',
            field=models.CharField(blank=True, help_text='Xero Connection id', max_length=255, null=True),
        ),
    ]
