# Generated by Django 3.1.14 on 2022-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0004_tenantmapping_connection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_tax_code_id',
            field=models.CharField(help_text='Xero default Tax Code ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_tax_code_name',
            field=models.CharField(help_text='Xero default Tax Code name', max_length=255, null=True),
        ),
    ]
