# Generated by Django 3.0.3 on 2020-12-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0002_auto_20201117_0655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destinationattribute',
            table='destination_attributes',
        ),
        migrations.AlterModelTable(
            name='expenseattribute',
            table='expense_attributes',
        ),
        migrations.AlterModelTable(
            name='mapping',
            table='mappings',
        ),
        migrations.AlterModelTable(
            name='mappingsetting',
            table='mapping_settings',
        ),
    ]
