# Generated by Django 3.0.3 on 2021-01-27 12:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0003_auto_20201221_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationattribute',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Detailed destination attributes payload', null=True),
        ),
        migrations.AddField(
            model_name='expenseattribute',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Detailed expense attributes payload', null=True),
        ),
    ]
