# Generated by Django 3.0.3 on 2021-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0005_expenseattribute_auto_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationattribute',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Indicates whether the field is auto created by the integration'),
        ),
        migrations.AddField(
            model_name='expenseattribute',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Indicates whether the field is auto created by the integration'),
        ),
    ]
