# Generated by Django 3.0.3 on 2021-04-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0006_auto_20210305_0827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destinationattribute',
            unique_together={('destination_id', 'attribute_type', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseattribute',
            unique_together={('value', 'attribute_type', 'workspace')},
        ),
    ]
