# Generated by Django 3.0.3 on 2021-07-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0009_auto_20210618_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingsetting',
            name='expense_field_id',
        ),
    ]
