# Generated by Django 3.0.3 on 2021-07-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('fyle_accounting_mappings', '0010_remove_mappingsetting_expense_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('destination_card_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_card_account', to='fyle_accounting_mappings.DestinationAttribute')),
                ('destination_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_employee', to='fyle_accounting_mappings.DestinationAttribute')),
                ('destination_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_vendor', to='fyle_accounting_mappings.DestinationAttribute')),
                ('source_employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fyle_accounting_mappings.ExpenseAttribute')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'employee_mappings',
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_account', to='fyle_accounting_mappings.DestinationAttribute')),
                ('destination_expense_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_expense_head', to='fyle_accounting_mappings.DestinationAttribute')),
                ('source_category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fyle_accounting_mappings.ExpenseAttribute')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'category_mappings',
            },
        ),
    ]
