# Generated by Django 3.1.14 on 2022-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0013_auto_20220323_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsetting',
            name='source_placeholder',
            field=models.TextField(help_text='placeholder of source field', null=True),
        ),
    ]
