# Generated by Django 3.1.14 on 2022-04-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0014_mappingsetting_source_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemapping',
            name='source_employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_mapping', to='fyle_accounting_mappings.expenseattribute'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='fyle_accounting_mappings.expenseattribute'),
        ),
    ]
