# Generated by Django 3.1.14 on 2022-04-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0015_auto_20220412_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemapping',
            name='source_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_mapping', to='fyle_accounting_mappings.expenseattribute'),
        ),
    ]
