# Generated by Django 3.1.14 on 2022-04-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0016_auto_20220413_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping', to='fyle_accounting_mappings.expenseattribute'),
        ),
    ]
