# Generated by Django 3.1.14 on 2022-04-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0017_auto_20220419_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemapping',
            name='source_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeemapping', to='fyle_accounting_mappings.expenseattribute'),
        ),
    ]
