# Generated by Django 3.1.14 on 2023-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0018_auto_20220419_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseattribute',
            name='value',
            field=models.CharField(help_text='Value of expense attribute', max_length=1000),
        ),
    ]
