# Generated by Django 3.1.14 on 2023-04-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0021_auto_20230323_0557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destinationattribute',
            unique_together={('destination_id', 'attribute_type', 'workspace', 'display_name')},
        ),
    ]
