# Generated by Django 3.1.14 on 2023-09-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0022_auto_20230411_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='source_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='categorymapping', to='fyle_accounting_mappings.expenseattribute'),
        )
    ]
