# Generated by Django 3.2.14 on 2024-03-20 11:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0038_alter_workspace_onboarding_state'),
        ('fyle_accounting_mappings', '0024_auto_20230922_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttributesDeletionCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
                ('project_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'expense_attributes_deletion_cache',
            },
        ),
    ]
