# Generated by Django 3.0.3 on 2020-11-02 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='Bill Currency', max_length=255)),
                ('contact_id', models.CharField(help_text='Xero Contact', max_length=255)),
                ('reference', models.CharField(help_text='Bill ID', max_length=255)),
                ('date', models.DateTimeField(help_text='Bill date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_categories', django.contrib.postgres.fields.jsonb.JSONField(help_text='Save Tracking options', null=True)),
                ('item_code', models.CharField(help_text='Item code', max_length=255, null=True)),
                ('account_id', models.CharField(help_text='NetSuite account id', max_length=255)),
                ('description', models.TextField(help_text='Lineitem purpose')),
                ('amount', models.FloatField(help_text='Bill amount')),
                ('bill', models.ForeignKey(help_text='Reference to Bill', on_delete=django.db.models.deletion.PROTECT, to='xero.Bill')),
                ('expense', models.OneToOneField(help_text='Reference to Expense', on_delete=django.db.models.deletion.PROTECT, to='fyle.Expense')),
            ],
            options={
                'db_table': 'bill_lineitems',
            },
        ),
    ]
