# Generated by Django 3.0.3 on 2020-11-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='Bill Currency', max_length=255)),
                ('contact_id', models.CharField(help_text='Xero Contact', max_length=255)),
                ('reference', models.CharField(help_text='Bill ID', max_length=255)),
                ('date', models.DateTimeField(help_text='Bill date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
        ),
    ]
