# Generated by Django 3.0.3 on 2021-02-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0003_auto_20210201_1145'),
        ('workspaces', '0005_auto_20210201_1145'),
        ('xero', '0002_banktransaction_banktransactionlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_on_xero',
            field=models.BooleanField(default=False, help_text='Payment status in Xero'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_synced',
            field=models.BooleanField(default=False, help_text='Payment synced status'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(help_text='Linked Transaction ID ( Invoice ID )', max_length=255)),
                ('account_id', models.CharField(help_text='Payment Account', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
                ('workspace', models.ForeignKey(help_text='Workspace reference', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
