# Generated by Django 3.0.3 on 2021-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0003_auto_20210201_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=None, help_text='Amount'),
            preserve_default=False,
        ),
    ]
