# Generated by Django 3.0.3 on 2021-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0004_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionlineitem',
            name='description',
            field=models.TextField(help_text='Xero Bank Transaction LineItem description', null=True),
        ),
    ]
