# Generated by Django 3.1.13 on 2021-12-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0005_auto_20210308_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionlineitem',
            name='tracking_categories',
            field=models.JSONField(help_text='Save Tracking options', null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='tracking_categories',
            field=models.JSONField(help_text='Save Tracking options', null=True),
        ),
    ]
