# Generated by Django 3.1.14 on 2022-03-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0007_auto_20220329_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionlineitem',
            name='tax_amount',
            field=models.FloatField(help_text='Tax amount', null=True),
        ),
        migrations.AddField(
            model_name='banktransactionlineitem',
            name='tax_code',
            field=models.CharField(help_text='Tax Group ID', max_length=255, null=True),
        ),
    ]
