# Generated by Django 3.1.14 on 2022-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0008_auto_20220331_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='export_id',
            field=models.CharField(help_text='Export ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banktransactionlineitem',
            name='customer_id',
            field=models.CharField(help_text='Xero customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banktransactionlineitem',
            name='line_item_id',
            field=models.CharField(help_text='Xero line item id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='export_id',
            field=models.CharField(help_text='Export ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='customer_id',
            field=models.CharField(help_text='Xero customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='line_item_id',
            field=models.CharField(help_text='Xero line item id', max_length=255, null=True),
        ),
    ]
