# Generated by Django 3.2.14 on 2024-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0009_auto_20220614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_retired',
            field=models.BooleanField(default=False, help_text='Is Payment sync retried'),
        ),
    ]
