# Generated by Django 3.0.2 on 2020-01-07 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyle_rest_auth', '0003_auto_20200107_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthTokens',
            new_name='AuthToken',
        ),
    ]
