# Generated by Django 3.0.2 on 2020-01-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_rest_auth', '0004_auto_20200107_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='access_token',
        ),
    ]
