# Generated by Django 3.0.3 on 2020-12-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_rest_auth', '0005_remove_authtoken_access_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authtoken',
            table='auth_tokens',
        ),
    ]
