# Generated by Django 3.0.3 on 2020-11-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='fyle_org_id',
            field=models.CharField(help_text='org id', max_length=255, unique=True),
        ),
    ]
