# Generated by Django 3.0.3 on 2021-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auto_20210201_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_categories',
            field=models.BooleanField(default=False, help_text='Auto import Categories to Fyle'),
        ),
    ]
