# Generated by Django 3.0.3 on 2021-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspacegeneralsettings_import_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='auto_map_employees',
            field=models.CharField(help_text='Auto Map Employees from Xero to Fyle', max_length=50, null=True),
        ),
    ]
