# Generated by Django 3.0.3 on 2021-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspacegeneralsettings_auto_map_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='auto_create_destination_entity',
            field=models.BooleanField(default=False, help_text='Auto create contact'),
        ),
    ]
