# Generated by Django 3.0.3 on 2021-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspacegeneralsettings_auto_create_destination_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='map_merchant_to_contact',
            field=models.BooleanField(default=False, help_text='Map Merchant to Contact for CCC Expenses'),
        ),
    ]
