# Generated by Django 3.0.3 on 2021-10-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_workspace_cluster_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='cluster_domain',
        ),
        migrations.AddField(
            model_name='fylecredential',
            name='cluster_domain',
            field=models.CharField(help_text='Cluster domain', max_length=255, null=True),
        ),
    ]
