# Generated by Django 3.0.3 on 2021-10-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_auto_20211005_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='map_fyle_cards_xero_bank_account',
            field=models.BooleanField(default=False, help_text='Map Fyle Cards to Xero Bank Account'),
        ),
    ]
