# Generated by Django 3.1.14 on 2021-12-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_workspace_xero_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='map_fyle_cards_xero_bank_account',
        ),
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='skip_cards_mapping',
            field=models.BooleanField(default=False, help_text='Skip cards mapping'),
        ),
    ]
