# Generated by Django 3.1.14 on 2022-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_auto_20211217_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cluster_domain',
            field=models.CharField(help_text='Cluster domain', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_tax_codes',
            field=models.BooleanField(default=False, help_text='Auto import tax codes to Fyle', null=True),
        ),
        migrations.AddField(
            model_name='xerocredentials',
            name='company_name',
            field=models.CharField(help_text='QBO Company Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xerocredentials',
            name='country',
            field=models.CharField(help_text='QBO Country Name', max_length=255, null=True),
        ),
    ]
