# Generated by Django 3.1.14 on 2022-03-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_auto_20220329_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='cluster_domain',
        ),
    ]
