# Generated by Django 3.1.14 on 2022-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_remove_workspace_cluster_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerocredentials',
            name='country',
            field=models.CharField(help_text='Xero Country Name', max_length=255, null=True),
        ),
    ]
