# Generated by Django 3.1.14 on 2022-06-09 08:58

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_xerocredentials_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='charts_of_accounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_chart_of_accounts, help_text='list of chart of account types to be imported into Fyle', size=None),
        ),
    ]
