# Generated by Django 3.1.14 on 2022-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_workspacegeneralsettings_charts_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='xero_accounts_last_synced_at',
            field=models.DateTimeField(help_text='Xero Accounts last synced at time', null=True),
        ),
    ]
