# Generated by Django 3.1.14 on 2022-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0020_workspace_xero_accounts_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_customers',
            field=models.BooleanField(default=False, help_text='Auto import customers to Fyle'),
        ),
    ]
