# Generated by Django 3.1.14 on 2022-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_workspacegeneralsettings_import_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_vendors_as_merchants',
            field=models.BooleanField(default=False, help_text='Auto import vendors from xero as merchants to Fyle'),
        ),
    ]
