# Generated by Django 3.1.14 on 2022-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_workspacegeneralsettings_change_accounting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='auto_create_merchant_destination_entity',
            field=models.BooleanField(default=False, help_text='Auto create fyle merchnat as xero contact'),
        ),
    ]
