# Generated by Django 3.1.14 on 2022-09-09 12:06

import apps.workspaces.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_workspacegeneralsettings_auto_create_merchant_destination_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_state',
            field=models.CharField(choices=[('CONNECTION', 'CONNECTION'), ('EXPORT_SETTINGS', 'EXPORT_SETTINGS'), ('IMPORT_SETTINGS', 'IMPORT_SETTINGS'), ('ADVANCED_CONFIGURATION', 'ADVANCED_CONFIGURATION'), ('COMPLETE', 'COMPLETE')], default=apps.workspaces.models.get_default_onboarding_state, help_text='Onboarding status of the workspace', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='auto_map_employees',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('NAME', 'NAME'), ('EMPLOYEE_CODE', 'EMPLOYEE_CODE')], help_text='Auto Map Employees from Xero to Fyle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_general_settings', to='workspaces.workspace'),
        ),
    ]
