# Generated by Django 3.1.14 on 2022-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_auto_20221004_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='app_version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v1', help_text='App version', max_length=2),
        ),
        migrations.AddField(
            model_name='workspace',
            name='fyle_currency',
            field=models.CharField(help_text='Fyle Currency', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='xero_currency',
            field=models.CharField(help_text='Xero Currency', max_length=5, null=True),
        ),
    ]
