# Generated by Django 3.1.14 on 2022-10-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0028_lastexportdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ccc_last_synced_at',
            field=models.DateTimeField(help_text='Datetime when ccc expenses were pulled last', null=True),
        ),
    ]
