# Generated by Django 3.1.14 on 2022-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_auto_20221102_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='app_version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v2', help_text='App version', max_length=2),
        ),
    ]
