# Generated by Django 3.1.14 on 2023-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0032_workspacegeneralsettings_is_simplify_report_closure_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='is_simplify_report_closure_enabled',
            field=models.BooleanField(default=True, help_text='Simplify report closure is enabled'),
        ),
    ]
