# Generated by Django 3.1.14 on 2023-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0033_auto_20230315_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='additional_email_options',
            field=models.JSONField(default=list, help_text='Email and Name of person to send email'),
        ),
    ]
