# Generated by Django 3.1.14 on 2023-03-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0033_auto_20230321_0736'),
        ('workspaces', '0034_auto_20230320_0805'),
    ]

    operations = [
    ]
