# Generated by Django 3.1.14 on 2023-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0035_merge_20230321_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='additional_email_options',
            field=models.JSONField(default=list, help_text='Email and Name of person to send email', null=True),
        ),
    ]
