# Generated by Django 3.2.14 on 2024-11-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0038_alter_workspace_onboarding_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='change_accounting_period',
            field=models.BooleanField(default=True, help_text='Change the accounting period'),
        ),
    ]
