# Generated by Django 4.2.20 on 2025-04-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0042_auto_20250108_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='is_simplify_report_closure_enabled',
        ),
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='skip_cards_mapping',
        ),
    ]
