# Generated by Django 4.2.20 on 2025-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0043_remove_workspacegeneralsettings_is_simplify_report_closure_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='skip_accounting_export_summary_post',
            field=models.BooleanField(default=False, help_text='Skip posting accounting export summary'),
        ),
    ]
