# Generated by Django 4.2.20 on 2025-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_workspacegeneralsettings_skip_accounting_export_summary_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='is_real_time_export_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
