# Generated by Django 4.2.22 on 2025-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_workspaceschedule_is_real_time_export_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='unmapped_card_count',
            field=models.IntegerField(default=0, help_text='count of unmapped cards'),
        ),
    ]
