# Generated by Django 4.2.26 on 2025-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0047_featureconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureconfig',
            name='fyle_webhook_sync_enabled',
            field=models.BooleanField(default=True, help_text='Enable fyle attribute webhook sync'),
        ),
    ]
