# Generated by Django 4.2.27 on 2026-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0048_alter_featureconfig_fyle_webhook_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='org_settings',
            field=models.JSONField(default=dict, help_text='Org Settings'),
        ),
    ]
