data = {
    'bill_payload':{
        'VendorRef':{
            'value':'43'
        },
        'APAccountRef':{
            'value':'33'
        },
        'DepartmentRef':{
            'value':'None'
        },
        'TxnDate':'2022-01-21',
        'CurrencyRef':{
            'value':'USD'
        },
        'PrivateNote':'Reimbursable expense by ashwin.t@fyle.in on 2022-01-21 ',
        'Line':[
            {
                'Description':'ashwin.t@fyle.in - Travel - 2022-01-21 - C/2022/01/R/8 -  - https://staging.fyle.tech/app/main/#/enterprise/view_expense/txlPjmNxssq1?org_id=orGcBCVPijjO',
                'DetailType':'AccountBasedExpenseLineDetail',
                'Amount':60.0,
                'AccountBasedExpenseLineDetail':{
                    'AccountRef':{
                        'value':'57'
                    },
                    'CustomerRef':{
                        'value':'None'
                    },
                    'ClassRef':{
                        'value':'None'
                    },
                    'TaxCodeRef':{
                        'value':'None'
                    },
                    'TaxAmount':0.0,
                    'BillableStatus':'NotBillable'
                }
            }
        ]
    },
    'bank_transaction_payload':{
        'DocNumber':'E/2022/01/T/9',
        'PaymentType':'CreditCard',
        'AccountRef':{
            'value':'42'
        },
        'EntityRef':{
            'value':'58'
        },
        'DepartmentRef':{
            'value':'None'
        },
        'TxnDate':'2022-01-21',
        'CurrencyRef':{
            'value':'USD'
        },
        'PrivateNote':'Credit card expense by ashwin.t@fyle.in on 2022-01-21 ',
        'Credit':False,
        'Line':[
            {
                'Description':'ashwin.t@fyle.in - Travel - 2022-01-21 - C/2022/01/R/8 -  - https://staging.fyle.tech/app/main/#/enterprise/view_expense/txvh8qm7RTRI?org_id=orGcBCVPijjO',
                'DetailType':'AccountBasedExpenseLineDetail',
                'Amount':30.0,
                'AccountBasedExpenseLineDetail':{
                    'AccountRef':{
                        'value':'57'
                    },
                    'CustomerRef':{
                        'value':'None'
                    },
                    'ClassRef':{
                        'value':'None'
                    },
                    'TaxCodeRef':{
                        'value':'None'
                    },
                    'TaxAmount':0.0,
                    'BillableStatus':'NotBillable'
                }
            }
        ]
    },
    'bill_response':{
        'DueDate':'2020-01-14',
        'Balance':1000.0,
        'domain':'QBO',
        'sparse':False,
        'Id':'146',
        'SyncToken':'0',
        'MetaData':{
            'CreateTime':'2020-01-14T02:18:29-08:00',
            'LastUpdatedTime':'2020-01-14T02:18:29-08:00'
        },
        'DocNumber':'rphZKTDmSLU2',
        'TxnDate':'2020-01-14',
        'CurrencyRef':{
            'value':'USD',
            'name':'United States Dollar'
        },
        'PrivateNote':'Report None / rphZKTDmSLU2 approved on 2020-01-14',
        'Line':[
            {
                'Id':'1',
                'LineNum':1,
                'Description':'Testing',
                'Amount':1000.0,
                'DetailType':'AccountBasedExpenseLineDetail',
                'AccountBasedExpenseLineDetail':{
                    'AccountRef':{
                        'value':'2',
                        'name':'Retained Earnings'
                    },
                    'BillableStatus':'NotBillable',
                    'TaxCodeRef':{
                        'value':'NON'
                    }
                }
            }
        ],
        'VendorRef':{
            'value':'56',
            'name':'Gokul'
        },
        'APAccountRef':{
            'value':'33',
            'name':'Accounts Payable (A/P)'
        },
        'TotalAmt':1000.0
    }
}