name: Continuous Deployment

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

jobs:
  staging_deploy:
    if: (github.event_name == 'push' && github.ref == 'master') || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'deploy')
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build and push docker image
        run: |
          echo '127.0.0.1  kubernetes' | sudo tee -a /etc/hosts
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          export NEW_TAG="v$(git rev-parse --short HEAD)";
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fyle_xero-api:$NEW_TAG .
          echo "Pushing Docker Image to Docker Hub";
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fyle_xero-api:$NEW_TAG
          echo "NEW_TAG=v$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG";
          sed -i "s?{{RELEASE_VERSION}}?${NEW_TAG}?" deployment/staging/controller.yml;
          sed -i "s?{{DOCKERHUB_USERNAME}}?${DOCKERHUB_USERNAME}?" deployment/staging/controller.yml;
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Deploy to Staging
        uses: fylein/aws-eks-deploy-action@master
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
          LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          EKS_KUBECTL_ROLE: ${{ secrets.EKS_KUBECTL_ROLE }}
          ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Staging Deploy Status - ${{ job.status }}
          SLACK_TITLE: Deploy Xero API to Staging
          SLACK_ICON_EMOJI: ":pepeok:"
          SLACK_USERNAME: NSAPI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ''
