name: Deploy Private Branch to Any Environment

on:
  pull_request:
    types: [labeled]

jobs:
  private_deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && contains(fromJSON('["staging_deploy","drstrange_deploy","c1_qa_deploy","c1_staging_deploy"]'), github.event.label.name)
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.label.name == 'c1_qa_deploy' && 'QA' || 'Staging' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: push to dockerhub
        uses: fylein/docker-release-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: fyle_xero-api

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Clone another repository
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.STAGING_DEPLOY_REPO }}
          ref: master
          path: ${{ vars.STAGING_DEPLOY_REPO }}
          persist-credentials: false
          token: ${{ secrets.DEPLOY_GIT_ACCESS_TOKEN }}

      - name: Update Image Tag
        run: |
          NEW_TAG="v$(git rev-parse --short HEAD)"
          if [[ "${{ github.event.label.name }}" == "staging_deploy" ]]; then
            cd ${{ vars.STAGING_DEPLOY_REPO }}/${{ vars.STAGING_DEPLOY_DIR }}/staging/integrations
          elif [[ "${{ github.event.label.name }}" == "drstrange_deploy" ]]; then
            cd ${{ vars.STAGING_DEPLOY_REPO }}/${{ vars.STAGING_DEPLOY_DIR }}/drstrange/integrations
          elif [[ "${{ github.event.label.name }}" == "c1_qa_deploy" ]]; then
            cd ${{ vars.STAGING_DEPLOY_REPO }}/${{ vars.C1_STAGING_DEPLOY_DIR }}/qa/integrations
          elif [[ "${{ github.event.label.name }}" == "c1_staging_deploy" ]]; then
            cd ${{ vars.STAGING_DEPLOY_REPO }}/${{ vars.C1_STAGING_DEPLOY_DIR }}/staging/integrations
          fi
          kustomize edit set image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fyle_xero-api=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fyle_xero-api:$NEW_TAG

      - name: Commit and push changes
        run: |
          cd ${{ vars.STAGING_DEPLOY_REPO }}/
          git config --global user.email "integrations@fylehq.com"
          git config --global user.name "GitHub Actions"
          git add .
          if [[ "${{ github.event.label.name }}" == "staging_deploy" ]]; then
            git commit -m "Deployed fyle_xero-api:$NEW_TAG to staging"
          elif [[ "${{ github.event.label.name }}" == "drstrange_deploy" ]]; then
            git commit -m "Deployed fyle_xero-api:$NEW_TAG to drstrange"
          elif [[ "${{ github.event.label.name }}" == "c1_qa_deploy" ]]; then
            git commit -m "Deployed fyle_xero-api:$NEW_TAG to c1-qa"
          elif [[ "${{ github.event.label.name }}" == "c1_staging_deploy" ]]; then
            git commit -m "Deployed fyle_xero-api:$NEW_TAG to c1-staging"
          fi
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_GIT_ACCESS_TOKEN }}@github.com/${{ vars.STAGING_DEPLOY_REPO }}
          git pull origin master
          git push origin master
