data = {
    'workspace_general_settings_payload':{
        'id':2,
        'reimbursable_expenses_object':'PURCHASE BILL',
        'corporate_credit_card_expenses_object':'BANK TRANSACTION',
        'is_simplify_report_closure_enabled': True,
        'sync_fyle_to_xero_payments':False,
        'sync_xero_to_fyle_payments':True,
        'map_merchant_to_contact':True,
        'change_accounting_period':True,
        'import_categories':True,
        'auto_map_employees':'EMAIL',
        'auto_create_destination_entity':True,
        'skip_cards_mapping':False,
        'import_tax_codes':True,
        'import_customers':False,
        'created_at':'2022-08-02T20:25:24.644164Z',
        'updated_at':'2022-08-02T20:25:24.644209Z',
        'auto_create_merchant_destination_entity': False,
        'charts_of_accounts':[
            'EXPENSE', 'SAMPLE'
        ],
        'workspace':2
    },
    'workspace':{
        'id':2,
        'name':'Fyle For MS Dynamics Demo',
        'fyle_org_id':'orNoatdUnm1w',
        'onboarding_state': 'CONNECTION',
        'xero_short_code':'None',
        'last_synced_at':'None',
        'ccc_last_synced_at':'None',
        'fyle_currency':'USD',
        'xero_currency':'USD',
        'app_version': 'v1',
        'source_synced_at':'None',
        'destination_synced_at':'None',
        'xero_accounts_last_synced_at':'None',
        'created_at':'2022-08-16T10:38:22.395750Z',
        'updated_at':'2022-08-16T10:38:22.395806Z',
        'user':[
            1
        ]
    },
    'expenses':[
        {
            'id':91,
            'employee_email':'ashwin.t@fyle.in',
            'employee_name':'Joanna',
            'category':'Food',
            'sub_category':None,
            'project':'Aaron Abbott',
            'org_id':'or79Cob97KSh',
            'expense_id':'txxTi9ZfdepC',
            'expense_number':'E/2022/05/T/16',
            'claim_number':'C/2022/05/R/4',
            'amount':50.0,
            'currency':'USD',
            'foreign_amount':None,
            'foreign_currency':None,
            'tax_amount':None,
            'tax_group_id':None,
            'settlement_id':'setDiksMn83K7',
            'reimbursable':True,
            'billable':False,
            'exported':False,
            'state':'PAYMENT_PROCESSING',
            'vendor':'Ashwin',
            'cost_center':'Marketing',
            'purpose':None,
            'report_id':'rpViBmuYmAgw',
            'corporate_card_id':None,
            'file_ids':[
                
            ],
            'spent_at':'2022-05-13T17:00:00Z',
            'approved_at':'2022-05-13T09:30:13.484000Z',
            'posted_at':'2022-05-13T17:00:00Z',
            'expense_created_at':'2022-05-13T09:29:43.535468Z',
            'expense_updated_at':'2022-05-13T09:32:06.643941Z',
            'created_at':'2022-05-23T11:11:28.241406Z',
            'updated_at':'2022-05-23T11:11:28.241440Z',
            'fund_source':'PERSONAL',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at':'2022-05-23T11:11:28.241440Z',
            'custom_properties':{
                'Team':'',
                'Class':'',
                'Klass':'',
                'Location':'',
                'Team Copy':'',
                'Tax Groups':'',
                'Departments':'',
                'Team 2 Postman':'',
                'User Dimension':'',
                'Location Entity':'',
                'Operating System':'',
                'System Operating':'',
                'User Dimension Copy':'',
                'Custom Expense Field':'None'
            },
            'paid_on_qbo':False,
            'payment_number':'P/2022/05/R/7'
        }
    ],
    'workspace_schedule': {
        'id':1,
        'enabled':True,
        'start_datetime':'2022-08-19T07:50:07.591198Z',
        'interval_hours':1,
        'workspace':1,
        'schedule':7,
        'additional_email_options': [],
        'emails_selected': None,
        'error_count': None
    }
}